"use client";

import { useState, useEffect, useCallback } from "react";
import Link from "next/link";
import {
  excuses,
  categoryLabels,
  categoryEmojis,
  languageLabels,
  languageFlags,
  uiStrings,
  type ExcuseCategory,
  type ExcuseLanguage,
} from "@/data/excuses";

const FREE_USES = 3;
const STORAGE_KEY_USES = "excuse-gen-uses";
const STORAGE_KEY_LICENSE = "excuse-gen-license";

export default function ExcuseApp() {
  const [language, setLanguage] = useState<ExcuseLanguage>("en");
  const [category, setCategory] = useState<ExcuseCategory>("boss");
  const [currentExcuse, setCurrentExcuse] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [displayedText, setDisplayedText] = useState("");
  const [usesLeft, setUsesLeft] = useState(FREE_USES);
  const [showPaywall, setShowPaywall] = useState(false);
  const [isUnlocked, setIsUnlocked] = useState(false);
  const [licenseInput, setLicenseInput] = useState("");
  const [showLicenseForm, setShowLicenseForm] = useState(false);
  const [licenseError, setLicenseError] = useState("");
  const [copied, setCopied] = useState(false);
  const [shared, setShared] = useState(false);
  const [shake, setShake] = useState(false);
  const [canNativeShare, setCanNativeShare] = useState(false);

  const ui = uiStrings[language];

  useEffect(() => {
    const savedUses = localStorage.getItem(STORAGE_KEY_USES);
    const savedLicense = localStorage.getItem(STORAGE_KEY_LICENSE);

    if (savedLicense) {
      setIsUnlocked(true);
    } else if (savedUses) {
      setUsesLeft(Math.max(0, FREE_USES - parseInt(savedUses, 10)));
    }

    setCanNativeShare(typeof navigator !== "undefined" && !!navigator.share);
  }, []);

  const typeExcuse = useCallback((text: string) => {
    setDisplayedText("");
    let i = 0;
    const interval = setInterval(() => {
      setDisplayedText(text.slice(0, i + 1));
      i++;
      if (i >= text.length) {
        clearInterval(interval);
      }
    }, 20);
    return () => clearInterval(interval);
  }, []);

  const generateExcuse = useCallback(() => {
    if (!isUnlocked) {
      const usedCount = parseInt(
        localStorage.getItem(STORAGE_KEY_USES) || "0",
        10
      );
      if (usedCount >= FREE_USES) {
        setShowPaywall(true);
        setShake(true);
        setTimeout(() => setShake(false), 500);
        return;
      }
      const newCount = usedCount + 1;
      localStorage.setItem(STORAGE_KEY_USES, newCount.toString());
      setUsesLeft(Math.max(0, FREE_USES - newCount));
    }

    setIsGenerating(true);
    setCopied(false);

    const pool = excuses[language][category];
    let excuse = pool[Math.floor(Math.random() * pool.length)];
    while (excuse === currentExcuse && pool.length > 1) {
      excuse = pool[Math.floor(Math.random() * pool.length)];
    }

    setTimeout(() => {
      setCurrentExcuse(excuse);
      setIsGenerating(false);
      typeExcuse(excuse);
    }, 600);
  }, [language, category, currentExcuse, isUnlocked, typeExcuse]);

  const copyExcuse = useCallback(() => {
    if (!currentExcuse) return;
    const text = `${currentExcuse}\n\n— Generated by StupidApps.io`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [currentExcuse]);

  const shareExcuse = useCallback(() => {
    if (!currentExcuse) return;
    const text = `${currentExcuse}\n\n— Generated by StupidApps.io`;

    if (canNativeShare) {
      navigator.share({ text }).catch(() => {});
    } else {
      navigator.clipboard.writeText(text);
      setShared(true);
      setTimeout(() => setShared(false), 2000);
    }
  }, [currentExcuse, canNativeShare]);

  const validateLicense = useCallback(async () => {
    if (!licenseInput.trim()) return;
    setLicenseError("");

    try {
      const res = await fetch("/api/license", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          key: licenseInput.trim(),
          appSlug: "excuse-generator",
        }),
      });

      if (res.ok) {
        localStorage.setItem(STORAGE_KEY_LICENSE, licenseInput.trim());
        setIsUnlocked(true);
        setShowPaywall(false);
        setShowLicenseForm(false);
      } else {
        setLicenseError("Invalid license key. Please check and try again.");
      }
    } catch {
      setLicenseError("Something went wrong. Please try again.");
    }
  }, [licenseInput]);

  const categories = Object.keys(
    excuses[language]
  ) as ExcuseCategory[];
  const languages = Object.keys(languageLabels) as ExcuseLanguage[];

  return (
    <div className="max-w-2xl mx-auto px-4 py-8 relative">
      {/* Header */}
      <div className="text-center mb-8">
        <Link
          href="/apps/excuse-generator"
          className="text-sm text-foreground/50 hover:text-foreground transition-colors mb-4 inline-block"
        >
          &larr; {ui.back}
        </Link>
        <div className="text-6xl mb-4 animate-float">🤥</div>
        <h1 className="text-3xl md:text-4xl font-extrabold mb-2">
          {ui.title.split(" ")[0]}{" "}
          <span className="gradient-text">
            {ui.title.split(" ").slice(1).join(" ")}
          </span>
        </h1>
        <p className="text-foreground/50">{ui.subtitle}</p>
      </div>

      {/* Language Selector */}
      <div className="flex justify-center gap-2 mb-6">
        {languages.map((lang) => (
          <button
            key={lang}
            onClick={() => {
              setLanguage(lang);
              setCurrentExcuse(null);
              setDisplayedText("");
            }}
            className={`px-3 py-2 rounded-lg text-sm font-medium transition-all ${
              language === lang
                ? "bg-primary/20 border border-primary/40 text-white"
                : "bg-card border border-white/5 text-foreground/50 hover:border-white/20"
            }`}
          >
            <span className="mr-1.5">{languageFlags[lang]}</span>
            {languageLabels[lang]}
          </button>
        ))}
      </div>

      {/* Category Selector */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-8">
        {categories.map((cat) => (
          <button
            key={cat}
            onClick={() => setCategory(cat)}
            className={`px-4 py-3 rounded-xl font-medium text-sm transition-all ${
              category === cat
                ? "bg-primary text-white shadow-lg shadow-primary/30 scale-105"
                : "bg-card border border-white/10 text-foreground/70 hover:border-primary/30 hover:bg-card-hover"
            }`}
          >
            <span className="text-lg block mb-1">{categoryEmojis[cat]}</span>
            {categoryLabels[language][cat]}
          </button>
        ))}
      </div>

      {/* Generate Button */}
      <div className="text-center mb-8">
        <button
          onClick={generateExcuse}
          disabled={isGenerating}
          className={`relative bg-accent hover:bg-accent-light text-black font-bold px-12 py-5 rounded-2xl text-xl transition-all active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed ${
            shake ? "animate-[shake_0.5s_ease-in-out]" : ""
          } ${!isGenerating ? "animate-pulse-glow" : ""}`}
        >
          {isGenerating ? (
            <span className="flex items-center gap-2">
              <svg
                className="animate-spin h-5 w-5"
                viewBox="0 0 24 24"
                fill="none"
              >
                <circle
                  className="opacity-25"
                  cx="12"
                  cy="12"
                  r="10"
                  stroke="currentColor"
                  strokeWidth="4"
                />
                <path
                  className="opacity-75"
                  fill="currentColor"
                  d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"
                />
              </svg>
              {ui.generating}
            </span>
          ) : (
            ui.generate
          )}
        </button>

        {/* Usage Counter */}
        {!isUnlocked && (
          <p className="text-sm text-foreground/40 mt-3">
            {usesLeft > 0 ? (
              <>
                {usesLeft} {usesLeft === 1 ? ui.freeUse : ui.freeUses}
              </>
            ) : (
              <span className="text-accent">{ui.trialEnded}</span>
            )}
          </p>
        )}
        {isUnlocked && (
          <p className="text-sm text-green-400 mt-3">{ui.unlimited}</p>
        )}
      </div>

      {/* Excuse Display */}
      {currentExcuse && (
        <div className="bg-card border border-white/10 rounded-2xl p-6 mb-6 min-h-[120px]">
          <p className="text-lg leading-relaxed text-foreground/90">
            &ldquo;{displayedText}&rdquo;
          </p>
          {displayedText === currentExcuse && (
            <div className="flex gap-3 mt-4 pt-4 border-t border-white/5">
              <button
                onClick={copyExcuse}
                className="flex items-center gap-2 text-sm text-foreground/50 hover:text-foreground transition-colors px-3 py-1.5 rounded-lg hover:bg-white/5"
              >
                {copied ? ui.copied : ui.copy}
              </button>
              <button
                onClick={shareExcuse}
                className="flex items-center gap-2 text-sm text-foreground/50 hover:text-foreground transition-colors px-3 py-1.5 rounded-lg hover:bg-white/5"
              >
                {shared
                  ? ui.copiedToShare
                  : canNativeShare
                  ? ui.share
                  : ui.copyToShare}
              </button>
            </div>
          )}
        </div>
      )}

      {/* Paywall Overlay */}
      {showPaywall && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-surface border border-white/10 rounded-2xl p-8 max-w-md w-full text-center">
            <div className="text-5xl mb-4">🔒</div>
            <h2 className="text-2xl font-extrabold mb-2">
              You&apos;ve Used All 3 Free Excuses!
            </h2>
            <p className="text-foreground/60 mb-6">
              Unlock unlimited excuses for all modes and languages. One-time
              purchase. No subscriptions. No accountability required.
            </p>
            <div className="text-3xl font-extrabold gradient-text mb-6">
              $3.99
            </div>
            <form action="/api/checkout" method="POST" className="mb-4">
              <input type="hidden" name="appSlug" value="excuse-generator" />
              <button
                type="submit"
                className="w-full bg-accent hover:bg-accent-light text-black font-bold px-8 py-4 rounded-xl text-lg transition-colors"
              >
                Unlock Unlimited Excuses
              </button>
            </form>

            <button
              onClick={() => setShowLicenseForm(!showLicenseForm)}
              className="text-sm text-foreground/40 hover:text-foreground/60 transition-colors"
            >
              Already purchased? Enter license key
            </button>

            {showLicenseForm && (
              <div className="mt-4 flex gap-2">
                <input
                  type="text"
                  value={licenseInput}
                  onChange={(e) => setLicenseInput(e.target.value)}
                  placeholder="Enter your license key"
                  className="flex-1 bg-card border border-white/10 rounded-lg px-4 py-2 text-sm focus:outline-none focus:border-primary/50"
                />
                <button
                  onClick={validateLicense}
                  className="bg-primary hover:bg-primary-light text-white font-medium px-4 py-2 rounded-lg text-sm transition-colors"
                >
                  Activate
                </button>
              </div>
            )}
            {licenseError && (
              <p className="text-red-400 text-sm mt-2">{licenseError}</p>
            )}

            <button
              onClick={() => setShowPaywall(false)}
              className="block mx-auto mt-4 text-sm text-foreground/30 hover:text-foreground/50 transition-colors"
            >
              Close
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
